title:  "Parag Bhatnagar"
tagline: "Personal Website"
description:

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'parag-bhatnagar'

menu:
- {name: 'Art', folder: 'pages', file: 'art.html'}
- {name: 'Design', folder: 'pages', file: 'design.html'}
- {name: 'Blog', folder: 'pages', file: 'blog.html'}
# - {name: 'Random Thoughts', folder: 'pages', file: 'posts.html'}
# - {name: 'Doc', folder: 'pages', file: 'documentation.html'}
- {name: 'About Me', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

social:
- {icon: 'fab fa-lg fa-facebook-square', link: 'https://www.facebook.com/paragbhtngr'}
- {icon: 'fab fa-lg fa-instagram', link: 'https://instagram.com/paragbhtngr'}
- {icon: 'fab fa-lg fa-github', link: 'https://github.com/paragbhtngr'}
- {icon: 'fas fa-lg fa-envelope', link: 'mailto:paragbhtngr@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
